services:
  - type: web
    name: medi-book-web
    runtime: static
    region: oregon
    plan: starter
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        value: https://medi-book-api.onrender.com  # Update this with your actual backend URL after deployment